accounts:
  - example account
userAgent: "-"
gggClientPath: C:\Program Files (x86)\Grinding Gear Games\Path of Exile\logs\Client.txt
steamClientPath: C:\Program Files (x86)\Steam\steamapps\common\Path of Exile\logs\Client.txt
epicClientPath: C:\Program Files (x86)\Epic Games\EpicLibrary\PathOfExile\logs\Client.txt
